# Generated by Django 3.2 on 2021-06-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_joblisting_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='category',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='published_on',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='user',
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='Salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
